import {
    AlertTriangle,
    ArrowRight,
    Check,
    ChevronLeft,
    ChevronRight,
    CircuitBoardIcon,
    Command,
    CreditCard,
    File,
    FileText,
    HelpCircle,
    Image,
    Laptop,
    LayoutDashboardIcon,
    Loader2,
    LogIn,
    LucideIcon,
    LucideProps,
    LucideShoppingBag,
    Moon,
    MoreVertical,
    Pizza,
    Plus,
    Settings,
    SunMedium,
    Trash,
    Twitter,
    User,
    UserCircle2Icon,
    UserPen,
    UserX2Icon,
    Earth,
    Cctv,
    Dices,
    Trophy,
    Award,
    X,
    History,
    Signature,
    UserRoundCog,
  } from 'lucide-react';
  
  export type Icon = LucideIcon;
  
  export const Icons = {
    dashboard: LayoutDashboardIcon,
    logo: Command,
    login: LogIn,
    close: X,
    product: LucideShoppingBag,
    spinner: Loader2,
    kanban: CircuitBoardIcon,
    chevronLeft: ChevronLeft,
    chevronRight: ChevronRight,
    trash: Trash,
    employee: UserX2Icon,
    post: FileText,
    page: File,
    userPen: UserPen,
    user2: UserCircle2Icon,
    media: Image,
    settings: Settings,
    billing: CreditCard,
    ellipsis: MoreVertical,
    add: Plus,
    warning: AlertTriangle,
    user: User,
    arrowRight: ArrowRight,
    help: HelpCircle,
    pizza: Pizza,
    sun: SunMedium,
    moon: Moon,
    earth: Earth,
    laptop: Laptop,
    cctv: Cctv,
    dices: Dices,
    award: Award,
    trophy: Trophy,
    history: History,
    signature: Signature,
    userRoundCog:UserRoundCog,
  };
  